dico_cine ={"4":{"titre": "Les gardiens de la galaxie 3",
               "synopsis": "Les Gardiens de la Galaxie vont devoir combattre à nouveau Ayesha, la prêtresse des Souverains, faire face au créateur de Rocket qui veut le récupérer à tout prix et défier Adam Warlock prêt à tout pour les tuer.",
               "genre": "Film de super  héros - Aventure - Action - Science-fiction",
               "duree": "2h43",
               "acteurs": "Chris Pratt - Zoe Saldana - Will Poulter - Sean Gunn",
               "Seance1": "04/04 - 10h - VF",
               "Seance2": "07/04 - 13h - VF",
               "Seance3": "09/04 - 20h - VF"},
           "1":{"titre": "Ant man et la guepe",
               "synopsis": "Les super-héros et partenaires Scott Lang et Hope Van Dyne, alias Ant-Man et la Guêpe, vont vivre de nouvelles aventures. En compagnie de Hank Pym et Janet Van Dyne, les parents de Hope, le duo va explorer la dimension subatomique, interagir avec d'étranges nouvelles créatures et se lancer dans une odyssée qui les poussera au-delà des limites de ce qu'il pensait être possible.",
               "genre": "Film de super héros - Aventure - Action - Science-fiction",
               "duree": "2h05",
               "acteurs": "Kathryn Newton - Jonathan Majors - Tony McCarthy - Paul Rudd",
               "Seance1":"03/04 - 10h - VF",
               "Seance2":"06/04 - 13h - VF",
               "Seance3":"08/04 - 20h - VF"},
           "2":{"titre": "Creed III",
               "synopsis": "Dominant toujours le monde de la boxe, Adonis Creed prospère dans sa carrière et sa vie de famille. Lorsque Damian, ami d'enfance et ancien prodige de la boxe, refait surface après avoir purgé une peine de prison, il a hâte de prouver qu'il mérite sa chance dans l'enceinte. La confrontation entre anciens amis est plus qu'un simple combat. Pour régler le compte, Adonis doit mettre son avenir en jeu pour combattre Damian, un combattant qui n'a rien à perdre.",
               "genre": "Action  - Film de sport - Drame",
               "duree": "1h56",
               "acteurs": "Michael B. Jordan - Jonathan Majors - Tessa Thompson",
               "Seance1":"03/04 - 13h - VF",
               "Seance2":"07/04 - 10h - VF",
               "Seance3":"07/04 - 20h - VF"},
           "3":{"titre": "Retour a seoul",
               "synopsis": "Sur un coup de tête, Freddie, 25 ans, retourne pour la première fois en Corée du Sud, où elle est née. La jeune femme se lance avec fougue à la recherche de ses origines dans ce pays qui lui est étranger, faisant basculer sa vie dans des directions nouvelles et inattendues.",
               "genre": "Drame",
               "duree": "1h58",
               "acteurs": "Park Ji- Min - Kim Sun-Young - Kwang-Rok Oh",
                "Seance1":"03/04 - 20h - VF",
               "Seance2":"04/04 - 13h - VF",
               "Seance3":"06/04 - 10h - VF"},
           "5":{"titre": "elementaire",
               "synopsis": "Le film suit les péripéties d'un couple improbable, Ember et Wade, dans une ville où les habitants - feu, eau, terre et air - vivent ensemble. Cette jeune femme enthousiaste et ce jeune homme discret sont sur le point de découvrir quelque chose d'élémentaire : ce qu'ils ont en commun",
               "genre": "animation",
               "duree": "1h50",
               "acteurs": "Mamoudou athie - Leath Lewis",
                "Seance1":"05/04 - 13h - VF",
               "Seance2":"08/04 - 13h - VF",
               "Seance3":"09/04 - 13h - VF"}}
