# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ecran_Choix.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Choix(object):
    def setupUi(self, Choix):
        Choix.setObjectName("Choix")
        Choix.resize(415, 403)
        Choix.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(Choix)
        self.centralwidget.setObjectName("centralwidget")
        self.Affiche_FIlm = QtWidgets.QLabel(self.centralwidget)
        self.Affiche_FIlm.setGeometry(QtCore.QRect(90, 0, 231, 191))
        self.Affiche_FIlm.setObjectName("Affiche_FIlm")
        self.PB_choix1 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_choix1.setGeometry(QtCore.QRect(40, 210, 331, 41))
        self.PB_choix1.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.PB_choix1.setObjectName("PB_choix1")
        self.PB_choix2 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_choix2.setGeometry(QtCore.QRect(40, 260, 331, 41))
        self.PB_choix2.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.PB_choix2.setObjectName("PB_choix2")
        self.PB_choix3 = QtWidgets.QPushButton(self.centralwidget)
        self.PB_choix3.setGeometry(QtCore.QRect(40, 310, 331, 41))
        self.PB_choix3.setStyleSheet("background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.PB_choix3.setObjectName("PB_choix3")
        Choix.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Choix)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 415, 21))
        self.menubar.setObjectName("menubar")
        Choix.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Choix)
        self.statusbar.setObjectName("statusbar")
        Choix.setStatusBar(self.statusbar)

        self.retranslateUi(Choix)
        QtCore.QMetaObject.connectSlotsByName(Choix)

    def retranslateUi(self, Choix):
        _translate = QtCore.QCoreApplication.translate
        Choix.setWindowTitle(_translate("Choix", "Choix Seances"))
        self.Affiche_FIlm.setText(_translate("Choix", "TextLabel"))
        self.PB_choix1.setText(_translate("Choix", "PushButton"))
        self.PB_choix2.setText(_translate("Choix", "PushButton"))
        self.PB_choix3.setText(_translate("Choix", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Choix = QtWidgets.QMainWindow()
    ui = Ui_Choix()
    ui.setupUi(Choix)
    Choix.show()
    sys.exit(app.exec_())
