# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\moleres\Documents\GitHub\projet-4-cinoche\paiment.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(518, 490)
        Dialog.setBaseSize(QtCore.QSize(0, 100))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.clb_retour = QtWidgets.QCommandLinkButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clb_retour.sizePolicy().hasHeightForWidth())
        self.clb_retour.setSizePolicy(sizePolicy)
        self.clb_retour.setToolTipDuration(-2)
        self.clb_retour.setObjectName("clb_retour")
        self.horizontalLayout.addWidget(self.clb_retour)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tl_code_carte = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tl_code_carte.sizePolicy().hasHeightForWidth())
        self.tl_code_carte.setSizePolicy(sizePolicy)
        self.tl_code_carte.setObjectName("tl_code_carte")
        self.horizontalLayout_2.addWidget(self.tl_code_carte)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tl_recapitulatif = QtWidgets.QLabel(Dialog)
        self.tl_recapitulatif.setObjectName("tl_recapitulatif")
        self.verticalLayout_2.addWidget(self.tl_recapitulatif)
        self.le_codesecret = QtWidgets.QLineEdit(Dialog)
        self.le_codesecret.setObjectName("le_codesecret")
        self.verticalLayout_2.addWidget(self.le_codesecret)
        self.tl_code_secret = QtWidgets.QLabel(Dialog)
        self.tl_code_secret.setObjectName("tl_code_secret")
        self.verticalLayout_2.addWidget(self.tl_code_secret)
        self.le_code_carte = QtWidgets.QLineEdit(Dialog)
        self.le_code_carte.setObjectName("le_code_carte")
        self.verticalLayout_2.addWidget(self.le_code_carte)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.clb_suivant = QtWidgets.QCommandLinkButton(Dialog)
        self.clb_suivant.setObjectName("clb_suivant")
        self.horizontalLayout_3.addWidget(self.clb_suivant)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.clb_retour.setText(_translate("Dialog", "Retour"))
        self.tl_code_carte.setText(_translate("Dialog", "TextLabel"))
        self.tl_recapitulatif.setText(_translate("Dialog", "Code carte bleu"))
        self.tl_code_secret.setText(_translate("Dialog", "Code secret"))
        self.clb_suivant.setText(_translate("Dialog", "Suivant"))
