# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\moleres\Documents\GitHub\projet-4-cinoche\remerciement.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_remerciment(object):
    def setupUi(self, remerciment):
        remerciment.setObjectName("remerciment")
        remerciment.resize(527, 351)
        font_titre= QtGui.QFont()
        font_titre.setFamily("Arial Black")
        font_titre.setPointSize(20)
        font_titre.setBold(True)
        font_titre.setWeight(75)

        font= QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)

        
        self.centralwidget = QtWidgets.QWidget(remerciment)
        remerciment.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Tl_logo = QtWidgets.QLabel(self.centralwidget)
        self.Tl_logo.setObjectName("Tl_logo")
        self.Tl_logo.setStyleSheet("color: white")
        self.Tl_logo.setFont(font_titre)
                           
        self.horizontalLayout.addWidget(self.Tl_logo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.Tl_num_reservation = QtWidgets.QLabel(self.centralwidget)
        self.Tl_num_reservation.setObjectName("Tl_num_reservation")
        self.Tl_num_reservation.setStyleSheet("color: white")
        self.Tl_num_reservation.setFont(font)
                           
        self.gridLayout_2.addWidget(self.Tl_num_reservation, 3, 0, 1, 1)
        self.Tl_remerciement = QtWidgets.QLabel(self.centralwidget)
        self.Tl_remerciement.setObjectName("Tl_remerciement")
        self.Tl_remerciement.setStyleSheet("color: white")
        self.Tl_remerciement.setFont(font)
        

        self.gridLayout_2.addWidget(self.Tl_remerciement, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        remerciment.setCentralWidget(self.centralwidget)

        

        self.retranslateUi(remerciment)
        QtCore.QMetaObject.connectSlotsByName(remerciment)

    def retranslateUi(self, remerciment):
        _translate = QtCore.QCoreApplication.translate
        remerciment.setWindowTitle(_translate("remerciment", "MainWindow"))
        self.Tl_logo.setText(_translate("remerciment", "Ciné Flash"))
        self.Tl_num_reservation.setText(_translate("remerciment", "TextLabel"))
        self.Tl_remerciement.setText(_translate("remerciment", "Merci pour votre réservation !!!"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    

    remerciement = QtWidgets.QMainWindow()
    ui = Ui_remerciment()
    ui.setupUi(remerciement)
    remerciement.show()
    sys.exit(app.exec_())
